apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: bank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank
        image: bharath0812/java:1.0
        ports:
        - containerPort: 8081
